import "./globals.css";

export const metadata = {
  title: "Chat Gpt",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="flex">
        {/* sidebar */}

        {/* client provider */}
        <div className="bg-[#343541] flex-1">{children}</div>
      </body>
    </html>
  );
}
